- name: Setup C/C++ Compiler
on:
  pull_request:
    branches:
    - master
  # You may pin to the exact commit or the version.
  # uses: rlalik/setup-cpp-compiler@06fe9cc0d7e8c7ea1702d497f0892430c34914ef
  uses: rlalik/setup-cpp-compiler@v1.1
  with:
    # Compiler to install
    compiler: latest
    
      matrix:
        os-version: [ windows-latest ]
        compiler: [ latest, gcc-latest, gcc-6.4.0, gcc-10.2.0, g++-11.2.0, clang, clang-8.0.0, clang-11.1.0, clang++-12.0.1 ]
